### ISSUE TITLE
Rename Repository to Ivelt Android App

### ISSUE THREAD

**Issue by KnaperYaden** [KFMDMSolutions/Ivelt-Android-App#1]
Thanks for this project!

I think that for clarity's sake it'd be useful to have this repo named **Ivelt Android App** and not just **_Ivelt_**.

**Comment by KFMDMSolutions** [comment]
> Thanks for this project!
> 
> I think that for clarity's sake it'd be useful to have this repo named **Ivelt Android App** and not just **_Ivelt_**.
Done.
