### ISSUE TITLE
Zoom Support

### ISSUE THREAD

**Issue by meilechh** [KFMDMSolutions/Ivelt-Android-App#10]
Thanks for creating this app.
I think it would be a good idea to support zoom.
Check this out https://developer.android.com/reference/android/webkit/WebSettings#setBuiltInZoomControls(boolean)

**Comment by KFMDMSolutions** [comment]
> Thanks for creating this app.
> I think it would be a good idea to support zoom.
> Check this out https://developer.android.com/reference/android/webkit/WebSettings#setBuiltInZoomControls(boolean)

done
