### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by KFMDMSolutions** [KFMDMSolutions/Ivelt-Android-App#11]
upload from camera doesn't work

**Comment by bevekashaivelt** [comment]
There are a few issues with upload from camera, however even if it were to work, additional code would still be needed to compress the picture down to 250kb (the max iVelt allows). In my opinion, this feature is not that important. How many times does someone want to take a picture and want to upload it to iVelt right away? I would rather remove this feature now, and come back to it at a different time.

**Comment by bevekashaivelt** [comment]
I think this issue can be closed, it seems to be working fine. the only issue is with automatic compressing when the image is too large. I thought the max iVelt allowed was 250 KB, but this is not the case, as I was able to upload a 470 KB image. 

What is the max iVelt allows?

**Comment by KnaperYaden** [comment]
> I think this issue can be closed, it seems to be working fine. the only issue is with automatic compressing when the image is too large. I thought the max iVelt allowed was 250 KB, but this is not the case, as I was able to upload a 470 KB image.
> 
> What is the max iVelt allows?

Approximately (at least) 600 KB in my tests.

**Comment by kavhayushar** [comment]
The front-end has a config section specifying `max_file_size: '768000b'`. But if I remember correctly, the php backend has a slightly different number.

**Comment by KnaperYaden** [comment]
> The front-end has a config section specifying `max_file_size: '768000b'`. But if I remember correctly, the PHP backend has a slightly different number.

I was able to upload now a 743 KB (761316b) PNG file, so can't be too a big difference.

**Comment by KFMDMSolutions** [comment]
> I think this issue can be closed, it seems to be working fine. the only issue is with automatic compressing when the image is too large. I thought the max iVelt allowed was 250 KB, but this is not the case, as I was able to upload a 470 KB image.
> 
> What is the max iVelt allows?

cloesed
