### ISSUE TITLE
2.4 Pre-release Can't Install APK

### ISSUE THREAD

**Issue by KnaperYaden** [KFMDMSolutions/Ivelt-Android-App#17]
I tried to install the 2.4 Pre-release APK.

On my flip phone it works fine.

But on my Motorola smartphone I first get this pop-up:
![Screenshot_20210722-032506](https://user-images.githubusercontent.com/87161728/126603899-62a6de48-6f9e-4d03-826e-2eabda1a90fe.png)
Even if I press Install Anyway it fails to install:
![Screenshot_20210722-033408-912](https://user-images.githubusercontent.com/87161728/126604169-2899b842-7924-45a5-8a99-8d124bd10d41.png)

What can be the issue?

**Comment by KFMDMSolutions** [comment]
try this one 
https://github.com/KFMDMSolutions/Ivelt-Android-App/releases/tag/2.4
i updated it with the new fix
https://github.com/KFMDMSolutions/Ivelt-Android-App/pull/16

and i singed it as debug

let me know if it fixes the issue

**Comment by KFMDMSolutions** [comment]
> I tried to install the 2.4 Pre-release APK.
> 
> On my flip phone it works fine.
> 
> But on my Motorola smartphone I first get this pop-up:
> ![Screenshot_20210722-032506](https://user-images.githubusercontent.com/87161728/126603899-62a6de48-6f9e-4d03-826e-2eabda1a90fe.png)
> Even if I press Install Anyway it fails to install:
> ![Screenshot_20210722-033408-912](https://user-images.githubusercontent.com/87161728/126604169-2899b842-7924-45a5-8a99-8d124bd10d41.png)
> 
> What can be the issue?

try this one
https://github.com/KFMDMSolutions/Ivelt-Android-App/releases/tag/2.4
i updated it with the new fix
#16

and i singed it as debug

let me know if it fixes the issue

**Comment by YisroelTech** [comment]
> try this one
> https://github.com/KFMDMSolutions/Ivelt-Android-App/releases/tag/2.4
> i updated it with the new fix
> #16
> 
> and i singed it as debug
> 
> let me know if it fixes the issue

Same thing.

**Comment by KnaperYaden** [comment]
> try this one
> https://github.com/KFMDMSolutions/Ivelt-Android-App/releases/tag/2.4
> i updated it with the new fix
> #16
> 
> and i singed it as debug
> 
> let me know if it fixes the issue

Same error 🙁

**Comment by KFMDMSolutions** [comment]
> > try this one
> > https://github.com/KFMDMSolutions/Ivelt-Android-App/releases/tag/2.4
> > i updated it with the new fix
> > #16
> > and i singed it as debug
> > let me know if it fixes the issue
> 
> Same error 🙁

איך זעה
 די פראבלעם איז מיט די סיגנעטשאר

**Comment by KFMDMSolutions** [comment]
> > > try this one
> > > https://github.com/KFMDMSolutions/Ivelt-Android-App/releases/tag/2.4
> > > i updated it with the new fix
> > > #16
> > > and i singed it as debug
> > > let me know if it fixes the issue
> > 
> > 
> > Same error 🙁
> 
> איך זעה
> די פראבלעם איז מיט די סיגנעטשאר

@KnaperYaden try now again please

**Comment by KnaperYaden** [comment]
> @KnaperYaden try now again please

וואונדערבאר!

(In the future for such updates to the APK I think you should iterate the minor version numbers to distinguish.)
