### ISSUE TITLE
Cookies Issue

### ISSUE THREAD

**Issue by bevekashaivelt** [KFMDMSolutions/Ivelt-Android-App#22]
I am trying to figure out when and why the cookies are expiring.
The funny thing is, that the cookies are there, they are just not working.
The solution I implemented, does not seem to work. (Which was to sync android's cookies with Java's cookies)  

It seems to me to happen after I change WiFi networks. Anyone else have this experience?

I have a workaround, to save the username and password on the device, and to automatically sign in when the cookie expires.  Should I implement this workaround? Or should I not, due to security issues.

**Comment by bevekashaivelt** [comment]
I am thinking there might be a case where the cookie is updated, maybe to reflect the change in network. However I am not sure.

**Comment by bevekashaivelt** [comment]
OK, it could be that the issue was that I didn't update the notification request to use the updated cookie store. Too bad, I cannot make a commit at the moment, as it would break quite a few things. Hopefully it will be done today or tomorrow, and will update at that point. Leaving the issue open, as I am not sure it is resolved.

**Comment by bevekashaivelt** [comment]
This issue should not stop the release, as the issue is present also in the old version.

**Comment by KnaperYaden** [comment]
> I am trying to figure out when and why the cookies are expiring.
> The funny thing is, that the cookies are there, they are just not working.
> The solution I implemented, does not seem to work. (Which was to sync android's cookies with Java's cookies)
> 
> It seems to me to happen after I change WiFi networks. Anyone else have this experience?

Sometimes it happens when switching networks, but not always.

When killing the app (Recent>Swipe Up) it's also happening sometimes for me.
> I have a workaround, to save the username and password on the device, and to automatically sign in when the cookie expires. Should I implement this workaround? Or should I not, due to security issues.

I don't think it's that sensitive to be afraid of security issues. Perhaps have it as an optional setting.

**Comment by bevekashaivelt** [comment]
My issue is not about real security issues, my issue is about perceived security issues, just adding the option will make people say the app is stealing my username and password. Even if I were to post this question on iVelt, people will start saying it.

**Comment by KnaperYaden** [comment]
> My issue is not about real security issues, my issue is about perceived security issues, just adding the option will make people say the app is stealing my username and password. Even if I were to post this question on iVelt, people will start saying it.

I would to saw "screw them"... but I'm not saying it...

**Comment by bevekashaivelt** [comment]
I think what i'll do is add a button to the login page, געדענק אין עפפ.

**Comment by kavhayushar** [comment]
Is this issue new? I believe I've seen this issue on Mobile even before using the app.
(if I correctly read the source code) The way it works is it looks on two things combined.
It calculates the time passed from last use, as well it checks if the IP matches.
If IP does not match up AND time has elapsed more than X minutes then it requires a new login.

Me personally would want the App to automatically login for me.
As long the app syncs with Android's/Chrome's/Google's saved passwords, I have no issue to sign back it from time to time.

**Comment by KnaperYaden** [comment]
I've been using Chrome on Android for a long time and virtually never need to sign in again.

**Comment by bevekashaivelt** [comment]
I think it's a new issue, If you read the phpbb source code regarding cookies, can you tell me if there is such a thing as the cookie being updated? Because I think that is the issue, the cookie is updated, but the app doesn't update it.

**Comment by bevekashaivelt** [comment]
Often times when I open the app, it opens the first page just fine, but logs me out on the second page, that's why I think the issue is that the cookie isn't being updated.

**Comment by KnaperYaden** [comment]
> Often times when I open the app, it opens the first page just fine, but logs me out on the second page, that's why I think the issue is that the cookie isn't being updated.

Isn't that "first page" just what was opened last time before leaving the app (and it shows it wihtout even loading it anew? I think it is.

**Comment by kavhayushar** [comment]
Yup. Just tested.
I changed my Public IP, and on the next request to ivelt.com I got new "Set-Cookie" headers replenishing the session cookies.
Interesting observation. On the following request, the website appended the SID to the request URL as `https://www.ivelt.com/forum/viewtopic.php?p=2924422&sid=###############################` but only on one request, after that everything went back to normal.
Now I don't know if this SID param is required in the URL but we definitely need to use the new acquired cookies.

**Comment by kavhayushar** [comment]
The appended SID param is the same value as the session cookie.

**Comment by bevekashaivelt** [comment]
OK I want to see if changing the notification request to using the cookieManager instead of managing the cookies manually works, if not, i'll need to set it manually.

**Comment by bevekashaivelt** [comment]
After fixing the notifications request, I changed networks twice, and still did not lose the cookies, I made sure to swipe up the app before changing networks. It looks like that was the issue.

TBT, the loading library i am using (jSoup) didn't have any cookie management until July 10. It seems they added it just for the iVelt app.

**Comment by KFMDMSolutions** [comment]
when you click on a yiddishworld link you have to sign in again

**Comment by KnaperYaden** [comment]
> when you click on a yiddishworld link you have to sign in again

It's that way in a regaler browser as well (some use it to be signed in with two nicks at the same time....)

The only way to solve this would be by having the app save the creds and sign in for you (was already discussed.)

**Comment by bevekashaivelt** [comment]
After some testing I see the cookies issue is more or less resolved, only when the app is completely closed is there an issue, I know why the issue happens, will try to fix it soon
