### ISSUE TITLE
Play Protect Detection

### ISSUE THREAD

**Issue by KnaperYaden** [KFMDMSolutions/Ivelt-Android-App#24]
Why am I getting this when trying to install pre release 2.5?
![Screenshot_20210726-210822](https://user-images.githubusercontent.com/87161728/127079006-b9c0e7be-5cb8-4832-abaf-966a2a8b77c2.png)

**Comment by KFMDMSolutions** [comment]
> Why am I getting this when trying to install pre release 2.5?

i used the same kay i used for the one on the play store 
so i don't know

**Comment by KnaperYaden** [comment]
> > Why am I getting this when trying to install pre release 2.5?
> 
> i used the same key i used for the one on the play store
> so i don't know

Odd.

I clicked INSTALL ANYWAY (it first didn't install, I needed to uninstall the 2.4 release first) and then got this, so I submitted it:
![image](https://user-images.githubusercontent.com/87161728/127084837-02ca7c49-0010-4f29-b04b-5e50b4579a89.png)

**Comment by bevekashaivelt** [comment]
When I distribute test builds, I do so without any signature. It works after uninstalling the store version.
