### ISSUE TITLE
Log Email Address Incorrect

### ISSUE THREAD

**Issue by KnaperYaden** [KFMDMSolutions/Ivelt-Android-App#25]
@bevekashaivelt 

The email address the app is trying to send the log file to is bevekashivelt@gmail.com and it's not going thorough (error noon existing email, I also tried bevekashaivelt@gmail.com with an a and it's the same)

**Comment by KFMDMSolutions** [comment]
it needs be changed to bevakashivelt@gmail.com wrong  e  beve

**Comment by bevekashaivelt** [comment]
Yes I fixed it in the latest commit
