### ISSUE TITLE
app crashes if the notifications is on

### ISSUE THREAD

**Issue by KFMDMSolutions** [KFMDMSolutions/Ivelt-Android-App#27]
if the notifications is on
the app crashes after a few seconds
and you can't login only if you select געדענק מיך

**Comment by KFMDMSolutions** [comment]
if the notifications is on 
the app crashes after a few seconds 
and you can't login only if you select געדענק מיך

**Comment by bevekashaivelt** [comment]
Hmm, was able to get it to crash once, but not again. Do you have any more info on this crash?

**Comment by bevekashaivelt** [comment]
As for געדענק מיך I will have to debug that as well

**Comment by bevekashaivelt** [comment]
I think I'll change the HTML manipulation to the onPageFinished, rather than on the should override url.

**Comment by KFMDMSolutions** [comment]
>@bevekashaivelt 
super job as of now
