### ISSUE TITLE
Separate branches for flip and standard

### ISSUE THREAD

**Issue by bevekashaivelt** [KFMDMSolutions/Ivelt-Android-App#3]
I think some features don't make sense for flip, while they do make sense for standard android phones, so I would like to keep them separate, and maintain them separate. Should we do that?

**Comment by bevekashaivelt** [comment]
I see minSDK version is 16, can I change it to 24?

**Comment by KFMDMSolutions** [comment]
> I think some features don't make sense for flip, while they do make sense for standard android phones, so I would like to keep them separate, and maintain them separate. Should we do that?

you didn't change the layout file to androidX 

but i find that swipe refresh from the support library 
is better 
i had problems scrolling and needtoscroll  didn't fix it 100%

**Comment by bevekashaivelt** [comment]
What layout file did I not change? I think I did change it. 

The problems you had with swipeRefreshLayout, was on basic phones? or regular phones?

**Comment by KFMDMSolutions** [comment]
> I see minSDK version is 16, can I change it to 24?

**Comment by KFMDMSolutions** [comment]
> What layout file did I not change? I think I did change it.
> 
> The problems you had with swipeRefreshLayout, was on basic phones? or regular phones?

https://github.com/KFMDMSolutions/Ivelt-Android-App/blob/main/app/src/main/res/layout/activity_main.xml

**Comment by KFMDMSolutions** [comment]
> I think some features don't make sense for flip, while they do make sense for standard android phones, so I would like to keep them separate, and maintain them separate. Should we do that?
I'll leave the old branch for flip phones and will update the main branch 
is that fine with you?

**Comment by bevekashaivelt** [comment]
Yes, it's ok.
