### ISSUE TITLE
Notification Dismiss Option on Flip Phones

### ISSUE THREAD

**Issue by KnaperYaden** [KFMDMSolutions/Ivelt-Android-App#30]
On flip phones (at least my Kyocera DuraXV) when I get a notification there is no way to dismiss it except by pressing on it (which opens/reads the thread.)

Some other flip-phone apps have a Dismiss option by pressing one of the two buttons (top two buttons).

Maybe this can be added, it would be useful.

**Comment by bevekashaivelt** [comment]
Which apk are you using? The regular or the .cts version? I am asking because i might be able to differentiate between a flip phone and a regular phone using that info.

**Comment by YisroelTech** [comment]
I'm using 2.6 APK from here https://github.com/KFMDMSolutions/Ivelt-Android-App/releases/tag/2.6.

Where is there a download for a separate cts version? Why is there a need to differentiate (have two different apps) isn't it possible to just add it and for all the other phones (since they have no buttons) it's just not gonna be relevant.

**Comment by KnaperYaden** [comment]
I'm using 2.6 APK from here https://github.com/KFMDMSolutions/Ivelt-Android-App/releases/tag/2.6.

Where is there a download for a separate cts version? Why is there a need to differentiate (have two different apps) isn't it possible to just add it and for all the other phones (since they have no buttons) it's just not gonna be relevant.

**Comment by bevekashaivelt** [comment]
There is no need, however putting extra settings for no good reason is not the best experience. 

I was anyway thinking of adding buttons to the notification. Can you click notification buttons? The Service notification has a button "check now", can you click that?

**Comment by KnaperYaden** [comment]
Which Service notification?

**Comment by bevekashaivelt** [comment]
If you set the update time to less than 15 minutes. you should see a notification. That's the service notification.

**Comment by KnaperYaden** [comment]
Oh.

No, the Check Now button isn't available on the flip phone.

**Comment by KFMDMSolutions** [comment]
> On flip phones (at least my Kyocera DuraXV) when I get a notification there is no way to dismiss it except by pressing on it (which opens/reads the thread.)
> 
> Some other flip-phone apps have a Dismiss option by pressing one of the two buttons (top two buttons).
> 
> Maybe this can be added, it would be useful.

the problem is with the notification client of the phone you can't dismiss any notification not just the ivelt one

**Comment by KnaperYaden** [comment]
> the problem is with the notification client of the phone you can't dismiss any notification not just the ivelt one

There certainly is a way, and a lot of natives apps have a Dismiss option:
![messages_0 (2)](https://user-images.githubusercontent.com/87161728/128300687-532448e0-9ed9-4fec-8cf9-bac521037c38.png)
![messages_0](https://user-images.githubusercontent.com/87161728/128300689-97c83ac7-b9f9-4157-a289-9ae8b253d4d7.png)
![messages_0 (1)](https://user-images.githubusercontent.com/87161728/128300691-a54cf906-4740-48bb-9252-3bc8c47cb6da.png)

**Comment by KFMDMSolutions** [comment]
> > the problem is with the notification client of the phone you can't dismiss any notification not just the ivelt one
> 
> There certainly is a way, and a lot of natives apps have a Dismiss option:
> ![messages_0 (2)](https://user-images.githubusercontent.com/87161728/128300687-532448e0-9ed9-4fec-8cf9-bac521037c38.png)
> ![messages_0](https://user-images.githubusercontent.com/87161728/128300689-97c83ac7-b9f9-4157-a289-9ae8b253d4d7.png)
> ![messages_0 (1)](https://user-images.githubusercontent.com/87161728/128300691-a54cf906-4740-48bb-9252-3bc8c47cb6da.png)

oh..
i don't use this phone for calling/texting so i don't know 
but notification from whatsapp/telegram etc... also don't have a dismiss option

**Comment by KFMDMSolutions** [comment]
![image](https://user-images.githubusercontent.com/86687136/128305576-f6adba92-c0c4-4b63-956a-7a3c2e580a9b.png)
![photo_2021-08-05_02-57-41](https://user-images.githubusercontent.com/86687136/128305601-ee2a708a-ecc7-4ad0-86bd-9ffb7e117314.jpg)

**Comment by KnaperYaden** [comment]
> oh..
> i don't use this phone for calling/texting so i don't know
> but notification from whatsapp/telegram etc... also don't have a dismiss option

Yeah, true since they weren't made for flip/button phones.

What I was suggesting is that we implement this specific feature to have the Dismiss option/button.

**Comment by KFMDMSolutions** [comment]
> > oh..
> > i don't use this phone for calling/texting so i don't know
> > but notification from whatsapp/telegram etc... also don't have a dismiss option
> 
> Yeah, true since they weren't made for flip/button phones.
> 
> What I was suggesting is that we implement this specific feature to have the Dismiss option/button.

its definitely the problem with a setting in the phone not with the app
as i showed you that on the LG it does have the dismiss option

but as you there might bee a way to fix it like the other notifications

**Comment by bevekashaivelt** [comment]
Is it possible for you to send me the apk of any app that has the dismiss button? I would like to decompile it and see how they did it.

It's possible that they are using a private API, in which case I won't be able to replicate it.

**Comment by KFMDMSolutions** [comment]
its message+ 
https://drive.google.com/file/d/1KU3g-09FdG-OAT_ELzA01jH-31sr5wPO/view?usp=sharing

all others are most probably system-odex apps

**Comment by bevekashaivelt** [comment]
OK, I see they are simply setting a dismiss button. Could be that I will have to use their specific ID for the button to show up, regardless, I will try to replicate everything they do as best possible, and see if the dismiss button shows up.
