### ISSUE TITLE
My baby

### ISSUE THREAD

**Issue by bevekashaivelt** [KFMDMSolutions/Ivelt-Android-App#32]
Just wanted to explain why I am not doing much work on this lately, I had a baby boy this past Leil Shishi.

**Comment by mayim-chayim** [comment]
Mazel Tov
 אסאך אידיש נחת

**Comment by KFMDMSolutions** [comment]
> Mazel Tov
> אסאך אידיש נחת

**Comment by bevekashaivelt** [comment]
ברוכים תהיה

**Comment by bevekashaivelt** [comment]
איך מאך וואך נאכט מארגן נאכט אין מאנסי געגענט, פאר פרטים, פארשטייט זיך בלויז אויב מען איז גרייט פאר גילוי, ביטע פרעגן אין אישי.
