### ISSUE TITLE
Google Drive Download

### ISSUE THREAD

**Issue by PleaseSmileToday** [KFMDMSolutions/Ivelt-Android-App#70]
I used to be able to download videos from google drive links in the app. But since last week it comes up the לינק געבלאקט message.

**Comment by ChaimWieder** [comment]
It's because Google started to redirect downloads to https://drive-data-export.usercontent.google.com/ so this URL should also be white-listed.

From [here](https://www.ivelt.com/forum/viewtopic.php?p=4846512#p4846512)

**Comment by PleaseSmileToday** [comment]
I get that, but on a flip phone without a browser. Using the app to download doesn't go. can it be whitelisted in the published apk?

**Comment by ChaimWieder** [comment]
> I get that, but on a flip phone without a browser. Using the app to download doesn't go. can it be whitelisted in the published apk?

No one can edit the APK installed on your device.
The developer can white-list it, and publish a new release.

**Comment by PleaseSmileToday** [comment]
I know.
It was just a indirect way of asking for a new release...

**Comment by bevekashaivelt** [comment]
@KFMDMSolutions please update version and make a release, then this ticket can be closed.

**Comment by KFMDMSolutions** [comment]
thanks
